countries:                        
  France:                                     'True' 
  Cyprus:                                     'True'               
  Montenegro:                                 'True'
  Bulgaria:                                   'True'
  Bosnia & Herzegovina:                       'True'
  Turkey:                                     'True'
  Italy:                                      'True'
  Hungary:                                    'True'
  Croatia:                                    'True'
  Romania:                                    'True'
  Portugal:                                   'True'
  Spain:                                      'True'
  The former Yugoslav Republic of Macedonia:  'True'
  Greece:                                     'True'
  Albania:                                    'True'
  Serbia:                                     'True'
  Libyan Arab Jamahiriya:                     'True'
  Gibraltar:                                  'True'
  Ukraine:                                    'True'
  Lebanon:                                    'True'
  Algeria:                                    'True'
  West Bank:                                  'True'
  Syrian Arab Republic:                       'True'
  Morocco:                                    'True'
  Tunisia:                                    'True'
  Israel:                                     'True'
  Switzerland:                                'True'
  Jordan:                                     'True'
  Slovenia:                                   'True'
  Egypt:                                      'True'
  Andorra:                                    'True'
  Moldova, Republic of:                       'True'