_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 5
                - 53
                - 54
                - 55
            "2":
                - 1
                - 5
                - 53
                - 54
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.19
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
model:
    value:
        checkpoints: checkpoints/checkpoints_UNet2D_10_days
        drop_out_rate: "0.4"
        final_activation: None
        kernel_size: (3, 3)
        num_filters: '[32]'
        num_layers: "4"
        pool_size: (4, 4)
        threshold: "0.5"
        use_batchnorm: "True"
testing:
    value:
        checkpoint_path: checkpoints/checkpoints_UNet2D_10_days/model_epoch43.pth
        save_results_path: output/output_UNet2D
training:
    value:
        batch_size: "8"
        learing_rate: "1e-3"
        number_of_epochs: "60"
